rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-2.3
  - gemfiles/Gemfile.rails-3.0
  - gemfiles/Gemfile.rails-3.1
  - gemfiles/Gemfile.rails-3.2
matrix:
  exclude:
    - rvm: 1.8.7
    - gemfiles/Gemfile.rails-3.2
notifications:
  recipients:
    - michal.lomnicki@gmail.com
    - ronen@barzel.org
